### PR TITLE
Release v3.3.0

### PR DESCRIPTION
**Pull request by riccardone**
It's a long way to get this story fully complete. So maybe is better start with a first group of classes. I'll continue with all remaining pieces around the solution asap.

### CODE REVIEW

**Comment by pgermishuys** [comment]
Hey @riccardone thank you so much for the contribution.
Would you mind squashing the commits. It's easier to review that way and easier to pull into release notes.

**Comment by riccardone** [comment]
Yes, I can do that

2015-09-23 10:00 GMT+01:00 Pieter Germishuys <notifications@github.com>:

**Comment by pgermishuys** [comment]
Just saw this now @riccardone 
I do apologise if it wasn't clear, would you mind squashing those commits into a **single** commit?

**Comment by riccardone** [comment]
For future reference I've just used the following command to do the squash and set the first commit as pick and all others with the squash command
git rebase -i origin/release-v3.3.0~5 release-v3.3.0
and then pushed remotely
Let me know if it is not what you expect

**Comment by jen20** [comment]
Looks good to me. Thanks @riccardone!

**Pull request merged**
