### PR TITLE
Add VNodeState to cluster node stats

### PR DESCRIPTION
**Pull request by GojiSoft**
To allow querying of the state of each node in a cluster via the stats http endpoint, add current value of VNodeState to node stats. This allows cluster master\slave status to be monitored by external tools.

### CODE REVIEW

**Comment by GojiSoft** [comment]
Added additional commits to this branch to add scaled process cpu stats via the new stat "proc-cpuScaled".

Discussed in issue: https://github.com/EventStore/EventStore/issues/521

**Comment by jen20** [comment]
Can you squash and rebase this as single logical commits per PR? That will make it easier to pick into releases. Thanks

**Comment by GojiSoft** [comment]
Will do - made a bit of a dogs dinner of that one!

**Comment by GojiSoft** [comment]
Will submit new pull requests.

**Pull request closed without merging**
