### PR TITLE
move protogen to publicClasses false

### LINKED ISSUE #313: Embedded Server nuget missing `protobuf-net` dependency
It won't start without it.

 - [nuget](https://www.nuget.org/packages/EventStore.Client.Embedded/)
 - [required: protobuf-net](https://www.nuget.org/packages/protobuf-net/)

### PR DESCRIPTION
**Pull request by gregoryyoung**
fixes #313 I think

### CODE REVIEW

**Comment by jen20** [comment]
Turns out this isn't the issue - 15cd99b fixes it.

**Comment by gregoryyoung** [comment]
You need this as well as it moves proto stuff to private

**Comment by jen20** [comment]
`/internalize` does that as part of the ilmerge

**Comment by gregoryyoung** [comment]
Sure if you dont use them from outside. I would rather have the normal
build tell me about such problems than wait for a release to have an
ilmerge error

On Sat, Jan 10, 2015 at 8:43 PM, James Nugent <notifications@github.com>
wrote:

> /internalize does that as part of the ilmerge
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/pull/317#issuecomment-69466847>.
>



-- 
Studying for the Turing test

**Pull request closed without merging**
