### PR TITLE
There is an issue with 4.0 of NLog with packaged Event Store

### PR DESCRIPTION
**Pull request by pgermishuys**
Seems like it's related to https://github.com/NLog/NLog/issues/736
Reverted for now until a binary release of 4.0.1 is available. The version is now 3.2.1

### CODE REVIEW

**Comment by gregoryyoung** [comment]
Having profiled quite a bit around nlog I think we should consider tossing
it as a whole

On Fri, Jun 19, 2015 at 1:56 PM, Pieter Germishuys <notifications@github.com
> wrote:

> Seems like it's related to NLog/NLog#736
> <https://github.com/NLog/NLog/issues/736>
> Reverted for now until a binary release of 4.0.1 is available. The version
> is now 3.2.1
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/EventStore/EventStore/pull/530
> Commit Summary
>
>    - There is an issue with 4.0 of NLog
>
> File Changes
>
>    - *M* src/EventStore.Common/Log/NLogger.cs
>    <https://github.com/EventStore/EventStore/pull/530/files#diff-0> (10)
>    - *M* src/libs/NLog.dll
>    <https://github.com/EventStore/EventStore/pull/530/files#diff-1> (0)
>    - *M* src/libs/NLog.xml
>    <https://github.com/EventStore/EventStore/pull/530/files#diff-2>
>    (10475)
>
> Patch Links:
>
>    - https://github.com/EventStore/EventStore/pull/530.patch
>    - https://github.com/EventStore/EventStore/pull/530.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/pull/530>.
>



-- 
Studying for the Turing test

**Comment by dnauck** [comment]
@gregoryyoung Throwing NLog away because its too slow?

**Comment by gregoryyoung** [comment]
Have done some profiling over it... way too many allocations associated. Also the level of complexity is way higher than I would like.

**Comment by dnauck** [comment]
Ah ok, btw there is another issue here that has the same goal: #255

**Comment by gregoryyoung** [comment]
:+1: I don't consider it to be a high priority but I would love to never see another nlog config :smile:

**Comment by jen20** [comment]
:+1:

**Pull request merged**
