### PR TITLE
Reintroduce FileCheckpoints

### PR DESCRIPTION
**Pull request by hayley-jean**
Changed: Use file checkpoints on Linux and memory mapped checkpoints on Windows

### CODE REVIEW

**Review by jageall — APPROVED** [review]

**Review by jageall — APPROVED** [review]

**Comment by gregoryyoung** [comment]
Just as a bit of discussion ... There used to be memorymapped checkpoints a **very long** time ago (I implemented then).

If running with mmap checkpoints it was **measurably** more efficient to use a single checkpoint file that contained multiple checkpoints. If not clear writer/chaser/etc are different byte sections in the same mmap as opposed to using n mmaps as checkpoints are currently done with files. The difference measurable.

I think I never benchmarked doing the same on the file checkpoints directly but I would wager the same change might also be beneficial.

There were also some informal discussions about a slight change in how the checkpoints worked to instead move them into the footer of the current chunk (32 bytes). This needed to be tested but was perceived to possibly be faster especially when also mmapping the tfchunks. And ... it would simplify things like the file structure/back instruction/etc etc.

The main reason for not moving things forward IIRC was "lets look again at the next major release" as it would change the file formats and things like backup procedures etc which as we all know can be a bit of a pain :) 

It might be a good time to revisit the idea.

**Review by condron — DISMISSED** [review]
Looks good

**Review by timothycoleman — CHANGES_REQUESTED** [review]
lets just hold on this a sec while we investigate the performance. for me the regular file checkpoint flushes at half the rate of the memory mapped one (on ntfs), seemingly because the regular one is updating the modified time a lot

going to check the behaviour on zfs

we might want to reconsider the default depending on what we find

**Review by timothycoleman — APPROVED** [review]
Doing a simple write/flush/read loop on the checkpoints yielded the following.

We see the memorymapped version is quicker on windows but on linux they perform the same as each other, so choosing according to OS looks good, especially since this is the same behaviour as we had while it used to run on mono

```
USB PLATTER, NTFS
MemoryMappedFileCheckpoint did 200 flushes in 00:00:02.3359016. 86 flushes/second
RegularFileCheckpoint      did 200 flushes in 00:00:05.3217928. 38 flushes/second

NVME, NTFS
MemoryMappedFileCheckpoint did 10000 flushes in 00:00:03.1795682. 3,145 flushes/second
RegularFileCheckpoint      did 10000 flushes in 00:00:05.3865895. 1,856 flushes/second

aws zfs (gp2?) uncompressed
ath: /srv/eventstore/data/tim.chk
Flushes: 10000
MemoryMappedFileCheckpoint did 10000 flushes in 00:00:07.9647080. 1,256 flushes/second
RegularFileCheckpoint      did 10000 flushes in 00:00:08.4984878. 1,177 flushes/second

aws zfs gp3 uncompressed
Path: /srv/eventstore/data/tim.chk
Flushes: 10000
MemoryMappedFileCheckpoint did 10000 flushes in 00:00:08.5280754. 1,173 flushes/second
RegularFileCheckpoint      did 10000 flushes in 00:00:08.6633967. 1,154 flushes/second

aws zfs gp3 compressed
Path: /srv/eventstore/data/tim.chk
Flushes: 10000
MemoryMappedFileCheckpoint did 10000 flushes in 00:00:08.6426804. 1,157 flushes/second
RegularFileCheckpoint      did 10000 flushes in 00:00:08.4456759. 1,184 flushes/second
```

the checkpoints also performed the same as each other on ext4

**Review by timothycoleman — APPROVED** [review]

**Comment by gregoryyoung** [comment]
> Doing a simple write/flush/read loop on the checkpoints yielded the following.
> 
> We see the memorymapped version is quicker on windows but on linux they perform the same as each other, so choosing according to OS looks good, especially since this is the same behaviour as we had while it used to run on mono
> 
> ```
> USB PLATTER, NTFS
> MemoryMappedFileCheckpoint did 200 flushes in 00:00:02.3359016. 86 flushes/second
> RegularFileCheckpoint      did 200 flushes in 00:00:05.3217928. 38 flushes/second
> 
> NVME, NTFS
> MemoryMappedFileCheckpoint did 10000 flushes in 00:00:03.1795682. 3,145 flushes/second
> RegularFileCheckpoint      did 10000 flushes in 00:00:05.3865895. 1,856 flushes/second
> 
> aws zfs (gp2?) uncompressed
> ath: /srv/eventstore/data/tim.chk
> Flushes: 10000
> MemoryMappedFileCheckpoint did 10000 flushes in 00:00:07.9647080. 1,256 flushes/second
> RegularFileCheckpoint      did 10000 flushes in 00:00:08.4984878. 1,177 flushes/second
> 
> aws zfs gp3 uncompressed
> Path: /srv/eventstore/data/tim.chk
> Flushes: 10000
> MemoryMappedFileCheckpoint did 10000 flushes in 00:00:08.5280754. 1,173 flushes/second
> RegularFileCheckpoint      did 10000 flushes in 00:00:08.6633967. 1,154 flushes/second
> 
> aws zfs gp3 compressed
> Path: /srv/eventstore/data/tim.chk
> Flushes: 10000
> MemoryMappedFileCheckpoint did 10000 flushes in 00:00:08.6426804. 1,157 flushes/second
> RegularFileCheckpoint      did 10000 flushes in 00:00:08.4456759. 1,184 flushes/second
> ```
> 
> the checkpoints also performed the same as each other on ext4

There is also a DirectIOCheckpoint (perhaps named unbufferedcheckpoint) sitting around somewhere. It would be worth benchmarking this as well. I went through looking quickly but did not see it.

This would give you the 3 major IO mechanisms within the current checkpoint logic as a benchmark before looking at possible changes.

If it has been lost (its somewhere in history) I can re-implement it in all of a 15-30 minutes for testing most of the code is still there I just dont see the checkpoint directly.

**Review by jageall — APPROVED** [review]

**Comment by jageall** [comment]
@gregoryyoung our benchmarks show the direct IO option being the fastest, but there is a specific issue with msync on some linux file systems right now that we need to address quickly and as msync/fsync has shown to be comparable and prevents an up to 15 second completion delay , we will go with the file checkpoints (these are what used to run exclusively on mono anyway) to fix this and deal with directio separately.

**Pull request merged**
