### PR TITLE
Use ConvertToClientResolvedEvent instead of ResolvedIndexEvent

### LINKED ISSUE #823: ResolvedEvent has null OriginalPosition in embedded catchup-subscription to All
Causes the event to be skipped and not forwarded to client. Have a pr, but not sure if it breaks anything else.

### PR DESCRIPTION
**Pull request by PeterHageus**
This is fixes a problem with catchup-subscriptions using embedded
client. Don't know if there are other implications. fixes #823

### CODE REVIEW

**Comment by PeterHageus** [comment]
Yep, updated.

**Comment by pgermishuys** [comment]
Do you have a reproduction of the issue that you are seeing?

**Comment by PeterHageus** [comment]
Not as a unit test in es-source (can't find a fixture that acutally uses the embeddedsubscription), but there's a separate repro here: https://groups.google.com/d/msg/event-store/A5rpffuPOGc/EWyn0WR3EgAJ

**Comment by gregoryyoung** [comment]
The embedded tests inherit from the clientapi tests and can be found here:

https://github.com/EventStore/EventStore/tree/release-v3.6.0/src/EventStore.Core.Tests/ClientAPI/Embedded

On Thu, Mar 3, 2016 at 11:26 AM, Peter Hageus <notifications@github.com>
wrote:

> Not as a unit test in es-source (can't find a fixture that acutally uses
> the embeddedsubscription), but there's a separate repro here:
> https://groups.google.com/d/msg/event-store/A5rpffuPOGc/EWyn0WR3EgAJ
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/pull/824#issuecomment-191676066>
> .
>



-- 
Studying for the Turing test

**Comment by PeterHageus** [comment]
Those tests never hit the embedded subscription, they use their own connections:
https://github.com/EventStore/EventStore/blob/release-v3.6.0/src/EventStore.Core.Tests/ClientAPI/subscribe_to_all_catching_up_should.cs#L105

I tried changing them to using the member _conn, but still never hit any breakpoints in EmbeddedSubscriptionBase. Don't know if it's related to MiniNode, will try to look at that code later.

**Comment by PeterHageus** [comment]
Try commenting out this line:
https://github.com/EventStore/EventStore/blob/release-v3.6.0/src/EventStore.ClientAPI.Embedded/EmbeddedSubscriptionBase.cs#L71

The tests still passes

**Comment by pgermishuys** [comment]
We will have a look at the Embedded tests. They do appear to not be correct.

**Comment by gregoryyoung** [comment]
Most are it looks like some are not and need BuildConnection added.

On Thu, Mar 3, 2016 at 12:26 PM, Pieter Germishuys <notifications@github.com
> wrote:

> We will have a look at the Embedded tests. They do appear to not be
> correct.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/pull/824#issuecomment-191696309>
> .
>



-- 
Studying for the Turing test

**Comment by pgermishuys** [comment]
@gregoryyoung yes, find/replace incoming.

**Comment by PeterHageus** [comment]
Tried that, same result. EmbeddedSubscription isn't used. Haven't been able to work out the flow compared to connecting 'externally'.

**Comment by pgermishuys** [comment]
@PeterHageus this branch fails without your fix. Have a look
https://github.com/EventStore/EventStore/tree/embedded-test-connection

**Comment by pgermishuys** [comment]
@PeterHageus can you please squash your commits?

**Comment by PeterHageus** [comment]
@pgermishuys : OK, done. False alarm on the tests btw. Turned out to be resharpers shoddy testrunner giving a false positive. NUnit was correct.

**Comment by PeterHageus** [comment]
Made big mess, sorry. Will try to work it out, or do new pr.

**Pull request closed without merging**
