### PR TITLE
Periodically log esdb version on each node

### PR DESCRIPTION
**Pull request by dhingrak**
Added: Periodically log esdb version on each node

Fixes https://linear.app/eventstore/issue/DB-177/periodically-log-the-eventstore-version-on-single-node

### CODE REVIEW

**Comment by dhingrak** [comment]
This PR is using the FakeLogger() which is created in PR https://github.com/EventStore/EventStore/pull/3855. I will resolve conflicts when the other PR 3555 merge.

**Comment by timothycoleman** [comment]
tests need adjusting i think. space in 'eventstore'

`Expected: "Current version of EventStore is : "0.0.0.0" " But was: "Current version of Event Store is : "0.0.0.0" " -----------------------------------^`

**Comment by timothycoleman** [comment]
this can be rebased now that the other pr that uses the fake logger is merged

**Review by timothycoleman — APPROVED** [review]
thanks looks good :+1:

**Review by hayley-jean — APPROVED** [review]

**Pull request merged**
