### PR TITLE
Second PR for issue #454

### PR DESCRIPTION
**Pull request by NetChris**
This is the remainder of my effort on issue #454.  I seem to have reached the end of the code, scanning any textual output/exception messages.  Summary of changes:
- Wording oddities
- Replaced exclamation points with periods in exception messages.
- Misspellings/grammar
-TODOs re: guards in ReaderStrategy.Create()
- Removed redundancies (e.g. "Something is wrong" in an exception)
- Capitalization (if only to keep consistent with existing code)
- Removed contractions
- Removed a few curse words, in strings and in a couple of test method names. Not a personal statement, but I figured they should be "normalized" :)

### CODE REVIEW

**Comment by jen20** [comment]
:+1: looks good to me

**Comment by jen20** [comment]
Thanks @NetChris, must have been a highly tedious job :-)

**Comment by gregoryyoung** [comment]
+1

On Mon, May 11, 2015 at 1:29 PM, James Nugent <notifications@github.com>
wrote:

> Thanks @NetChris <https://github.com/NetChris>, must have been a highly
> tedious job :-)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/pull/477#issuecomment-100861197>
> .
>



-- 
Studying for the Turing test

**Comment by NetChris** [comment]
I'm happy to help.  It was highly enlightening.  Even skimming essentially all the code in this major project just shows me how mush I have to learn.  Thanks for the opportunity to work on this project, if only in a cleanup role.

**Pull request merged**
