### PR TITLE
Ability to disable index merges during busy periods.

### PR DESCRIPTION
**Pull request by megakid**
This is mainly a discussion point but if agreed, this is almost ready to go.
A few weeks ago we had an outage during a peak load period due to an index merge that was occurring on all the nodes within that particular cluster.  We saw SLOW MSG BUS messages stacking up in the logs and had no way to prevent the merge from occurring or to stop the merge once in progress.  

We feel the probability of merges occurring during peak periods is naturally higher (in terms of when they are likely to occur) due to the fact that the index is under more pressure due to the increased amount of events being added.  We discussed this internally and decided that the biggest win would be to suspend any index merges until after the peak period has passed.

I have exposed an admin POST endpoint to enable and disable the on-the-fly index merging.  The proposed setup we have discussed is that index merging is to be disabled during peak hours (we see this as 4 - 5 hours) and then re-enabled afterwards.  The toggle back to enabled would likely trigger a full merge soon afterwards.

This is a first effort that this.  Comments, suggestions, queries all welcome.

### CODE REVIEW

**Comment by jen20** [comment]
This looks like a reasonable approach to relieving some disk pressure, especially on larger databases, at the expense of index lookup time - which may be an acceptable trade off. @gregoryyoung any thoughts here?

**Comment by gregoryyoung** [comment]
How is this related?

https://github.com/EventStore/EventStore/pull/1488/files#diff-3765b6dad4f260935b2cde1764a5282eR82

**Comment by megakid** [comment]
@gregoryyoung I ended up with 3 endpoints all auth'ing on the same stuff - can revert that if necessary.

**Comment by megakid** [comment]
Also a potential enhancement, instead of exposing a simple `bool`.  I could configure index merging levels `int` e.g. only merge the first `n` levels, `0` would mean merging totally disabled (same as `false`).  This would enable some compromise by enabling some levels to be merged whilst not merging two 16 or 32Gb files - for example.  Too complex?  Thoughts?

**Comment by gregoryyoung** [comment]
(Taking the role of devil's advocate)

Might it be better to make the merge run slower by intention? Right now there is no throttling on it except what the OS pushes back.

**Comment by megakid** [comment]
We did discuss automatically determining when to disable index merging but wasn't sure what metric to use (and would probably vary wildly depending on hardware) - how would slowing down index merges look?  `Thread.Sleep()` ¯\\_(ツ)_/¯ ?

**Comment by gregoryyoung** [comment]
Thread.Sleep could work (as silly as it sounds). Where is your bottleneck IO/CPU (I am guessing IO)

**Comment by megakid** [comment]
Yes, I/O

**Comment by hayley-jean** [comment]
Hi @megakid 

Could you please re-open this against the `release-v4.1.1` branch
Thanks

**Pull request closed without merging**
