### PR TITLE
Improve Docker File

### PR DESCRIPTION
**Pull request by thefringeninja**
Fixed: Log to default directory; args from CLI

### CODE REVIEW

**Comment by sigil66** [comment]
General best practice for a docker container is to only log to standard out. It's curious we are mounting a volume there, if a customer want's to do this mounting and enabling a log volume should be conditional.

**Comment by thefringeninja** [comment]
@sigil66 I agree in principle, however stats are also logged to that folder (as opposed to being written to a stream in v5).

The other things that are logged to that folder (in json) is just a copy of the console logs (`file`), plus a dedicated error log (`err`). Unfortunately configuring serilog from a file with multiple targets is unnecessarily complicated.

For a future major release, I think a decent compromise is to use configuration to decide which of these logs you want to use, and for the container we turn off `file` and `err`. However that still leaves the `stats` log.

**Comment by alexeyzimarev** [comment]
Are planning to change the user to use the user id (1001) instead of the name?

**Comment by pgermishuys** [comment]
@alexeyzimarev shall we open an issue to deal with that or would you like it addressed in this PR?

**Comment by Lougarou** [comment]
@pgermishuys @alexeyzimarev it looks like we are assigning uid 1000 to eventstore. Does it have to be 1001?
The rest of the changes (log and ip) looks good to me

**Comment by alexeyzimarev** [comment]
I guess 1000 is fine

**Pull request merged**
