### PR TITLE
Implemented 494 issue: Projections ClientAPI map to objects

### PR DESCRIPTION
**Pull request by riccardone**
I implemented the story following the already existent UserManager implementation. 
I created a DTO class called ProjectionDetails that reflect the JSon results that I found. I don't know exactly the meaning of each field so I was not able to describe it in the field comment.
I wrote some integration tests in the following class:
EventStore.Core.Tests/ClientAPI/Projections/list_projections.cs 

The above changes break some tests that I fixed but I'm not able to run those tests right now because I don't have a test environment ready.
The tests are:
src/EventStore.Projections.Core.Tests/ClientAPI/specification_with_standard_projections_runnning.cs
src/EventStore.Projections.Core.Tests/ClientAPI/Cluster/specification_with_standard_projections_runnning.cs
and the fix that allow me to compile but probably need to be reviewd is:
all.Any(p => p.Name == "Faulted")

I also had to fix a problem with the EventStore.Padmin.Commands class that I end up fixing with the following code:
LogUnformatted(string.Join(" | ", manager.ListAllAsync(userCredentials).Result));
I did not found tests for this so I was not able to check properly this fix.

Cheers
Riccardo

### CODE REVIEW

**Comment by jen20** [comment]
Thanks @riccardone! We're just about to release v3.2.0, and this needs a bit more attention so we'll review and include it in the release after that?

**Comment by riccardone** [comment]
Yes it's fine for me

**Comment by riccardone** [comment]
@pgermishuys   Why closed?

**Comment by pgermishuys** [comment]
Hi @riccardone, I should have commented here.
Can you please open this PR against release-v3.3.0 ?

**Comment by riccardone** [comment]
Sure, I'll do it that asap. Same thing for #618 ticket?

**Comment by pgermishuys** [comment]
Nope, that PR was already merged into 3.2.0.

**Pull request closed without merging**
