### PR TITLE
Expose resignation of Master over HTTP. (Previously known as Maintenance Mode)

### PR DESCRIPTION
**Pull request by muzaffar**
Ref: #1170 

Adds the ability to issue a resignation of the master node over http. This command will generally be issued after the priority of master is set to a lower priority of the other nodes in the cluster.

This provides the ability to be able to perform maintenance tasks such as scavenging on the master without having to restart the master but issuing a resignation which will elect another member in the cluster as master.

#### Important Note
There is no UI bits for this and currently is only exposed via HTTP.

The process of resigning a master is a 2 step process.

#### Set node priority
We need to ensure that we set the node priority (this is a hint for when elections occur as it will select nodes based on a set of criteria and will order them by node priority amongst other things.) to a lower priority than the other nodes in the cluster.

```
curl -X POST -d{} http://x.x.x.x:1114/admin/node/priority/-1 -u admin:changeit
```

#### Issue a resignation of the current running master node
When a master node is given the instruction to resign, it will ensure that all the writes in flight are handled before it changes it's state from `Master` to `Unkown`. The intermediate state is `ResigningMaster`. During this state it will no longer accept any incoming writes.
```
curl -X POST -d{} http://x.x.x.x:1114/admin/node/resign -u admin:changeit
```

### CODE REVIEW

**Comment by ChrisChinchilla** [comment]
@muzaffar1331 Will this need docs? If so add the label…

**Comment by avish0694** [comment]
#1

Issue description:

Replica status blinks on the UI page

Steps to reproduce the issue: 

Enable maintenance mode on master node by launching node 

`curl -X POST http://127.0.0.1:1113/admin/maintenance/enable -u admin:changeit -H "Content-Length: 0”`


What's the expected result?
Replica status to show consistently on UI

What's the actual result?
Replica status on UI appearing and disappears when maintenance mode is enabled on master node


#2

Issue description:

Nodes shuts down when enable maintenance node. 


Steps to reproduce the issue: 

Enable maintenance mode on master node when eventstore client is writing data. 

`curl -X POST http://127.0.0.1:1113/admin/maintenance/enable -u admin:changeit -H "Content-Length: 0"`

What's the expected result?
Master node becomes slave. And new master is elected. (No shutdown)


What's the actual result?

2 nodes shuts down when EventStore client is writing events and maintenance mode is enabled on master node


#3

Issue description:

Nodes shuts down when you launch them in a 3 node cluster


Steps to reproduce the issue: 

 No consistent reproduction

What's the expected result?

3 nodes expected to join cluster and work.


What's the actual result?

Nodes shuts down when starting them

Stack trace: 
[ERROR] FATAL UNHANDLED EXCEPTION: System.IO.IOException: Invalid handle to path "/Users/avish/db2/chunk-000011.000000"
  at System.IO.FileStream.Dispose (System.Boolean disposing) [0x00052] in <98fac219bd4e453693d76fda7bd96ab0>:0
  at System.IO.Stream.Close () [0x00000] in <98fac219bd4e453693d76fda7bd96ab0>:0
  at System.IO.Stream.Dispose () [0x00000] in <98fac219bd4e453693d76fda7bd96ab0>:0
  at (wrapper remoting-invoke-with-check) System.IO.Stream.Dispose()
  at EventStore.Core.TransactionLog.Chunks.TFChunkBulkReader.Release () [0x0000b] in <95edd66a7030431fb85f1959116925b5>:0
  at EventStore.Core.TransactionLog.Chunks.TFChunkBulkReader.Dispose () [0x00009] in <95edd66a7030431fb85f1959116925b5>:0
  at EventStore.Core.TransactionLog.Chunks.TFChunkBulkReader.Finalize () [0x00000] in <95edd66a7030431fb85f1959116925b5>:0
1m%


Tested on Mac
Browser : Chrome

**Comment by muzaffar1331** [comment]
How to run the unit tests on Ubuntu 18.04:

`export FrameworkPathOverride=/usr/lib/mono/4.7.1-api && cd EventStore/src/EventStore.Core.Tests`

`dotnet test --filter EventStore.Core.Tests.Services.ElectionsService.ChoosingMasterTests`

**Comment by hayley-jean** [comment]
We are merging this PR for now, but there are improvements that need to be made to the election and gossip services in order to improve the stability of the cluster.

**Comment by mat-mcloughlin** [comment]
closed #1170

**Pull request merged**
