### PR TITLE
Ensure not override the filter when updating a persistent subscription (DB-315)

### PR DESCRIPTION
**Pull request by huynhhuuloc129**
Fixed: Updating a persistent subscription clears the filter

### CODE REVIEW

**Review by timothycoleman — COMMENTED** [review]
thanks!

- would you mind removing the extra whitespace changes that have been introduced on those empty lines
- there is a test failing at the moment
- an extra test that check that this fix works would be fab

**Review by timothycoleman — CHANGES_REQUESTED** [review]
thanks - i suspect something isn't quite right with the test because it passes even without the fix

**Comment by huynhhuuloc129** [comment]
> thanks - i suspect something isn't quite right with the test because it passes even without the fix
thank you, I'll check it

**Review by timothycoleman — APPROVED** [review]
great, thanks :+1:

**Review by hayley-jean — APPROVED** [review]

**Pull request merged**
