### PR TITLE
Increase the utility of PairingHeap

### PR DESCRIPTION
**Pull request by machonky**
Remove the need for #defines as well while increasing utility of the class with various node creation strategies.

### CODE REVIEW

**Comment by gregoryyoung** [comment]
Have you benchmarked?

**Comment by machonky** [comment]
Apologies - no.

**Comment by gregoryyoung** [comment]
There is most certainly a cost to the abstraction (and this is a reasonably hot area of code). This is mostly used in the timing service. We have since drastically reduced the amount of work it was doing so this is likely ok. 

It might also be worth looking at a hashed wheel for our use case.

On a side note for these kinds of implementations might it be useful to extract a common assembly that contains just such thing?

**Comment by machonky** [comment]
Agree about cost of abstraction. If it's a performance bottleneck, then a specific Object pool implementation is justified, otherwise code-re-use/maintainability approach wins (less code = better).
 
For me - new assemblies motivated only by proven re-use/decoupling need, otherwise build performance can suffer.

Perhaps greater value to project might be gained from some kind of performance suite that declares benchmarks for critical performance areas. Contributors can then test before & after code changes to determine a win. That said, benchmarks need Prod experience/judgement to be useful.

**Comment by gregoryyoung** [comment]
We will still consider this as a PR, it just needs to be benchmarked so we know the overall cost of the introduction

**Comment by machonky** [comment]
Sure. Look forward to outcome. Cheers.

**Pull request closed without merging**
