### PR TITLE
Add application/octet-stream in HTTP API to support just data events

### PR DESCRIPTION
**Pull request by pgermishuys**
This PR adds support for data only events. This will require the user to provide the `ES-EventType` header and the user cannot have metadata associated with the Event.

### CODE REVIEW

**Comment by hayley-jean** [comment]
When reading a stream that contains binary events with the body embedded, the events are returned as a utf8 string representation of the binary data.

@gregoryyoung any thoughts about this?

**Comment by pgermishuys** [comment]
@hayley-jean we don't actually know what format those events are in, the best we can do is to just give the user some representation of it.
I expect consumers to use the Event Type here to indicate what type of data is contained in these events and perform a request for the contents of that event with the appropriate accept header.

**Comment by gregoryyoung** [comment]
For embedded streams utf8 could work. This would give a side benefit of the UI somewhat working on these IIRC it uses embedded. The issue is we don't know whether this is XML or something else.

**Comment by hayley-jean** [comment]
Looks good

**Pull request merged**
