### PR TITLE
Feature/cross platform nugets

### PR DESCRIPTION
**Pull request by haf**
This is WIP. Don't merge. Going to ensure at least paths are OK on Windows, and rebase properly.

### CODE REVIEW

**Comment by gregoryyoung** [comment]
What are you hoping to do with this (I see all my unaligner stuff in here)

**Comment by haf** [comment]
Bad rebase. WIP.

**Comment by gregoryyoung** [comment]
ah ok no worries.

**Comment by gregoryyoung** [comment]
btw there is a program there called "unaligner" as you were running dev you will most likely need to run that program on your db coming back to 3.2.0 (there was an alignment change between dev and 3.0.5 etc)

**Comment by haf** [comment]
Fair enough. I suppose competing-etc doesn't need it though, as running the tool on data makes ES unable to start with hash errors. I'm looking forward to 3.2.0.

**Comment by gregoryyoung** [comment]
yes competing-etc is old dev. running 3.2.0 on current files will give hash error (unaligner will make them work in 3.2.0)

**Comment by jen20** [comment]
Just FYI, it's unlikely we'll take a dependency on Ruby to build. Everything else is just plain bash and powershell, with an emphasis on the required tools being in the repository so everything can be built with a single clone.

**Comment by haf** [comment]
You still don't have the dependency; only people wishing to build nugets on OS X, which you don't do, need it. So you're no worse off, but instead better off. I'm not building nugets with bash, it's too complex. Besides, ruby already is installed on all unix systems, so it's zero overhead.

**Comment by jen20** [comment]
It's not installed on ubuntu by default (nor should it be). Again, this is unlikely to get merged with any Ruby related things in it. If you must have a way of doing this, you'd be better off wrapping it as an external project and adding ES as a submodule.

**Comment by haf** [comment]
@jen20 You're just wrong.

```
➜  tmp  vagrant init ubuntu/trusty64
vagrant upA `Vagrantfile` has been placed in this directory. You are now
ready to `vagrant up` your first virtual environment! Please read
the comments in the Vagrantfile as well as documentation on
`vagrantup.com` for more information on using Vagrant.

➜  tmp  vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'ubuntu/trusty64' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Loading metadata for box 'ubuntu/trusty64'
    default: URL: https://atlas.hashicorp.com/ubuntu/trusty64
==> default: Adding box 'ubuntu/trusty64' (v20150817.0.0) for provider: virtualbox
    default: Downloading: https://atlas.hashicorp.com/ubuntu/boxes/trusty64/versions/20150817.0.0/providers/virtualbox.box
==> default: Successfully added box 'ubuntu/trusty64' (v20150817.0.0) for 'virtualbox'!
==> default: Importing base box 'ubuntu/trusty64'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'ubuntu/trusty64' is up to date...
==> default: Setting the name of the VM: tmp_default_1440161819254_13615
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 22 => 2222 (adapter 1)
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Connection timeout. Retrying...
    default:
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default:
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if it's present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
==> default: Mounting shared folders...
    default: /vagrant => /Users/h/dev/logibit/ops/dockerfiles/tmp
➜  tmp  vagrant ssh
Welcome to Ubuntu 14.04.3 LTS (GNU/Linux 3.13.0-62-generic x86_64)

 * Documentation:  https://help.ubuntu.com/

  System information as of Fri Aug 21 12:57:40 UTC 2015

  System load:  0.37              Processes:           78
  Usage of /:   2.8% of 39.34GB   Users logged in:     0
  Memory usage: 24%               IP address for eth0: 10.0.2.15
  Swap usage:   0%

  Graph this data and manage this system at:
    https://landscape.canonical.com/

  Get cloud support with Ubuntu Advantage Cloud Guest:
    http://www.ubuntu.com/business/services/cloud

0 packages can be updated.
0 updates are security updates.


vagrant@vagrant-ubuntu-trusty-64:~$ ruby --version
ruby 1.9.3p484 (2013-11-22 revision 43786) [x86_64-linux]
vagrant@vagrant-ubuntu-trusty-64:~$
```

**Comment by jen20** [comment]
```
$ vagrant ssh
Welcome to Ubuntu 14.04.2 LTS (GNU/Linux 3.16.0-30-generic x86_64)

 * Documentation:  https://help.ubuntu.com/
Last login: Fri Jul 17 14:15:46 2015 from 192.168.239.1
vagrant@packer-vmware-iso:~$ ruby
The program 'ruby' can be found in the following packages:
 * ruby
 * ruby1.8
Try: sudo apt-get install <selected package>
vagrant@packer-vmware-iso:~$
```

**Comment by jen20** [comment]
Doesn't look wrong to me, I believe this is also the case with several common base AMIs also (though unverified). Let me make this quite clear: we're not going to merge something that adds another build system in for ANY purpose.

**Comment by haf** [comment]
So, if you're using packer, your explicitly specifying your dependencies, so that's not the normal case. In the normal case, like I have shown you with the LTS official machine, ruby exists, as it should be.

On OS X it's also there by default.

Now, that horse is already beaten to death. It's there by default.

Given that, you said: "with an emphasis on the required tools being in the repository so everything can be built with a single clone.", let's look at how to build it: `bundle && bundle exec rake` with a single clone. That works too.

So given that I've refuted your arguments for not adding it, and given that it really helps people who are not on windows, why not add it as a couple of files in a subdirectory? It doesn't have to be in the root and it won't be in the way. Is it because you have something against me personally? Why don't you, instead of arguing and delaying me, look at the PR's code and comment on it; working together to make it possible to build nugets on OS X for everyone? Or are you going to close this like now, like you tend do when you feel that your point can't be proven?

**Comment by jen20** [comment]
I'm not objecting to the feature of a shell script to build nugets. I am objecting to your adding Ruby-related dependencies to a project which has nothing to do with Ruby. The minimal installation of server is what I am using to build, whether or not that suits your requirements.

**Comment by haf** [comment]
But you're not building nugets in it as you said yourself.

**Pull request closed without merging**
