### PR TITLE
Partial work on Issue #454

### PR DESCRIPTION
**Pull request by NetChris**
There's still more to do, but I didn't want to wait too long before a merge and PR.

### CODE REVIEW

**Comment by jen20** [comment]
Wow, great work! I'll look through this and get it merged ASAP. :+1:

**Comment by jen20** [comment]
Looks good to me, thanks @NetChris!

**Comment by jen20** [comment]
Whoops meant to link this to #454 instead of #460. Clearly not had enough coffee yet.

**Comment by gregoryyoung** [comment]
small issue I will just fix on dev (buffer manager exception should be "check in" was "checking" changed to "check"

**Comment by NetChris** [comment]
Happy to help.  And I'll keep going through the solution to find more.

**Pull request merged**
