### PR TITLE
Matsientst/invalid config closest match

### PR DESCRIPTION
**Pull request by matsientst**
Added: Suggestions for unknown/invalid configuration parameters (#3784)

This PR adds the feature to suggest a parameter when the user passes an incorrect parameter. For example, if the user passes a parameter like: `--cluster-sze` the system would suggest:
`The option "ClusterSze" is not a known option. Did you mean "ClusterSize"`

### CODE REVIEW

**Comment by ylorph** [comment]
I'd suggest either 
*  removing the dump of --help configuration settings when we detect something wrong
* inverting order : dump --help and the `FTL` message 
Eg: the following is correctly detected, though i have to scroll up quite a bit to be able to see the problem
.\EventStore.ClusterNode.exe --dev  --Advertise-Host-To-Client-s example.com

image

That's using the console ofc.
when using the logs it would help as well , as the default for most people is to look at the tail of the log first

**Comment by ylorph** [comment]
Also when using `allow unknown options` : `--dev  --Advertise-Host-To-Client-s example.com --allow-unknown-options true`
Shouldn't really be the log level WRN instead of INF  ? otherwise it will never be acted upon 

[24716, 1,10:21:19.195,INF] The option "AdvertiseHostToClientS" is not a known option. Did you mean "AdvertiseHostToClientAs"

**Review by hayley-jean — APPROVED** [review]
Looks good and works locally

I agree with @ylorph about the log changes, but I'm happy for that to be in a separate PR if you prefer

**Comment by timothycoleman** [comment]
Looks good to me too, and also agreed about yves suggestions for a separate PR (for context though, we originally chose INF rather tha WRN when unknown options are allowed because we were expecting it to be made use of in cloud and didn't want customers to have warnings that weren't their fault. i think this may no longer be applicable though.

I've pushed some suggestions, they're pretty minor just idomatic stuff mostly. if you're happy @matsientst then they can be squashed in

**Review by timothycoleman — CHANGES_REQUESTED** [review]
pushed some suggestions ^

**Comment by matsientst** [comment]
@timothycoleman Looks great! Changes squashed. Am I good to merge?

**Review by hayley-jean — APPROVED** [review]

**Pull request merged**
