### PR TITLE
Make the RequestManagementService thread safe

### PR DESCRIPTION
**Pull request by lscpike**
The RequestManagementService subscribes to the MainBus which can dispatch from many threads in parallel. The class uses a Dictionary which is not thread safe.

I've changed to use a ConcurrentDictionary. I'm not sure of the performance implications.

### CODE REVIEW

**Comment by gregoryyoung** [comment]
Maybe I misunderstand but main bus is single threaded.

**Comment by gregoryyoung** [comment]
To be more clear https://github.com/EventStore/EventStore/blob/dev/src/EventStore.Core/ClusterVNode.cs#L91

**Comment by lscpike** [comment]
We found this in testing showing up as an IndexOutOfRangeException.

I assumed that single threaded should be the case, but it almost certainly isn't at the moment.

Now you've confirmed that, I've done a quick scan. Looks like at least one place the contract is broken is MonitoringService.OnTimerTick. I'll leave it to somebody who knows the code base better to audit for more.

**Comment by gregoryyoung** [comment]
Ah ok I understand more now. Let me take a proper look at it. MainBus is
certainly single threaded however there are some odd places that are not
(and this is something I would like to resolve)

On Sat, Jun 6, 2015 at 11:06 PM, lscpike <notifications@github.com> wrote:

> We found this in testing showing up as an IndexOutOfRangeException.
>
> I assumed that single threaded should be the case, but it almost certainly
> isn't at the moment.
>
> Now you've confirmed that, I've done a quick scan. Looks like at least one
> place the contract is broken is MonitoringService.OnTimerTick. I'll leave
> it to somebody who knows the code base better to audit for more.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/pull/505#issuecomment-109644216>
> .
>



-- 
Studying for the Turing test

**Comment by gregoryyoung** [comment]
btw next week I am in london let's chat gregoryyyoung1 at google email.

On Sat, Jun 6, 2015 at 11:09 PM, Greg Young <gregoryyoung1@gmail.com> wrote:

> Ah ok I understand more now. Let me take a proper look at it. MainBus is
> certainly single threaded however there are some odd places that are not
> (and this is something I would like to resolve)
>
> On Sat, Jun 6, 2015 at 11:06 PM, lscpike <notifications@github.com> wrote:
>
>> We found this in testing showing up as an IndexOutOfRangeException.
>>
>> I assumed that single threaded should be the case, but it almost
>> certainly isn't at the moment.
>>
>> Now you've confirmed that, I've done a quick scan. Looks like at least
>> one place the contract is broken is MonitoringService.OnTimerTick. I'll
>> leave it to somebody who knows the code base better to audit for more.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/EventStore/EventStore/pull/505#issuecomment-109644216>
>> .
>>
>
>
>
> --
> Studying for the Turing test
>



-- 
Studying for the Turing test

**Comment by lscpike** [comment]
Apologies the MonitorService was actually using the queue correctly and not the bus.

I added a thread id check and debugged to find the incorrect usages. I've raised PR #506 to replace this.

**Pull request closed without merging**
