### PR TITLE
[DBX-78-6] Connectors docs: Small fixes

### PR DESCRIPTION
**Pull request by shaan1337**

### CODE REVIEW

**Comment by w1am** [comment]
LGTM!

**Comment by RagingKore** [comment]
@w1am fyi

**Review by coloradomorrissey — APPROVED** [review]

**Comment by coloradomorrissey** [comment]
@shaan1337 ready to merge.

**Review by YoEight — COMMENTED** [review]
Some of those changes will conflict with the changes what we have in another connectors documentation that we are working on.

**Comment by w1am** [comment]
@shaan1337 I added you as co author in #4574 . We can close this one if you'd like

**Review by coloradomorrissey — APPROVED** [review]

**Comment by shaan1337** [comment]
@w1am hey, sure, i'll close this one, thanks!

**Pull request closed without merging**
