### PR TITLE
Made fromCategories available from projections.

### PR DESCRIPTION
**Pull request by michielboekhoff**
@pgermishuys Here it is, opened on `release-v4.0.1`.

### CODE REVIEW

**Comment by pgermishuys** [comment]
@michielboekhoff thanks!

**Comment by pgermishuys** [comment]
@michielboekhoff sorry for not having merged this in for 4.0.1. 4.0.1 was re-purposed for a hot fix last week. This requires some tests.

**Comment by michielboekhoff** [comment]
@pgermishuys No problem. You mean you want me to add some tests for this PR?

**Comment by pgermishuys** [comment]
Yes please sir. The following is a good starting point. https://github.com/EventStore/EventStore/blob/release-v4.0.2/src/EventStore.Projections.Core.Tests/Services/v8/when_defining_a_v8_projection.cs#L11

**Comment by michielboekhoff** [comment]
@pgermishuys Why was this closed?

**Comment by pgermishuys** [comment]
It needs to be reopened against 4.0.1 as I tried to explain above. The 4.0.1 branch was repurposed.

**Comment by michielboekhoff** [comment]
@pgermishuys Ah, my apologies, I'd not fully awoken. I'll reopen and create tests.

**Comment by pgermishuys** [comment]
@michielboekhoff no problem and thanks! much appreciated! shout if you need some help with the tests.

**Pull request closed without merging**
