### PR TITLE
Fix By Correlation Id projection on link event appeared bug

### PR DESCRIPTION
**Pull request by Narvalex**
This is a bug that only happens when link events are written to the database. This is related to issue #1938 .

**Prerequisites:**

- Event Store version 5.0.1 
- All system projections enabled
- The following continuous projection enabled:
``` js
fromAll()
    .when({ 
        $any: (s, e) => {
            if (e.streamId.substring(0, 1) === '$')
                return;

            linkTo('all', e);
       }
})
```

**Symtomps:**
When appending events with correlation id, the stream `$bc-[correlationId]` appears with all the correlated events as expected.
After restarting the node we can see the stream `$bc-[correlationId]` is empty, and or not making progress.

**Root cause:**
The system projection appears to be handling the link events in disruptive way. Before the pull request #1882 link events where ignored. After that merge, link events are not ignored at all.

**Resolution:**
Ignore link events.

### CODE REVIEW

**Comment by pgermishuys** [comment]
Hey @Narvalex!
Thanks for taking the time to root cause this aswell as opening a PR.
Just letting you know that we have the issue on our V6 backlog. There will likely be a delay in getting to accepting and merging this PR.

Thank you once again!

**Comment by Narvalex** [comment]
Thanks for your kind words @pgermishuys ! Just letting you know that we have a custom build of Event Store with this pull request merge in production for several month now without any issues. Thanks you all for your hard work in this great database

**Comment by Narvalex** [comment]
Can someone help me with the failed build on Windows please? I cant understand why...

**Comment by YoEight** [comment]
Hi @Narvalex, don't worry about that windows build right now, it's a false negative. With your patch, did you stop having the issue mentioned in #1938 ?

I'm asking because I think #2447 should fix it but it's possible I missed something.

**Comment by Narvalex** [comment]
The #2447 prevents the `$by_correlationId` projection to get in a faulted state, but does not fix the issue, as described in the #1938 thread

**Pull request closed without merging**
