### PR TITLE
Allow use name of catch-up subscription in connection verbose logging

### PR DESCRIPTION
**Pull request by zabrowarnyrafal**

### CODE REVIEW

**Comment by pgermishuys** [comment]
@zabrowarnyrafal, would you mind opening the PR against the 4.0.2 branch. PRs should always be opened against the current active release branch.

Thanks!

**Comment by zabrowarnyrafal** [comment]
Np. - i just tough the next maintenance release would be v3.9.4 and it is  open for any fixes and improvements

**Comment by zabrowarnyrafal** [comment]
https://github.com/EventStore/EventStore/pull/1285

**Comment by hayley-jean** [comment]
Closing this in favour of the PR opened against 4.0.2

**Pull request closed without merging**
