### PR TITLE
Add Scavenge operation to Embedded Client

### LINKED ISSUE #1689: Add embedded client method for scavenge
Its a pretty small task but useful for people who may not expose tcp/http interfaces. Looking in the http client the message needed can be seen we just need a wrapper to raise the same message iternally from the embedded client.

### PR DESCRIPTION
**Pull request by shaan1337**
Fixes #1689

### CODE REVIEW

**Comment by shaan1337** [comment]
This will require some additional changes since this will probably conflict with this series of PRs: #1629

**Comment by pgermishuys** [comment]
@shaan1337 would you mind having a look at this again?

**Comment by pgermishuys** [comment]
This will require some rework!

**Comment by pgermishuys** [comment]
This PR has gone stale and will require some rework.

**Pull request closed without merging**
