### PR TITLE
Add missing Reset method to ProjectionsManager and ProjectionsClient

### PR DESCRIPTION
**Pull request by BredStik**
To close issue #1671

### CODE REVIEW

**Comment by BredStik** [comment]
Seems like AppVeyor build failed because of a unit test that has nothing to do with the code I changed (EventStore.Core.Tests.Integration.when_a_single_node_is_restarted_multiple_times.should_be_a_different_epoch_for_every_startup).  Can I do anything about it?

**Comment by avish0694** [comment]
@BredStik. Thanks for the PR. It looks good! I have restarted AppVeyor.

**Comment by ChrisChinchilla** [comment]
@avish0694 Docs updated, I'll push changes live when this is released, as the getting started guide was also waiting for this fix, and I don't want that to update if it doesn't work yet :)

**Comment by shaan1337** [comment]
@BredStik that's great, thanks!

**Pull request merged**
