### PR TITLE
Issue #278 rel links in user api

### PR DESCRIPTION
**Pull request by belczyk**
I added links on the single user level for edit,delete, reset password, change password, enable/disable. 
Links at the collection level can be easily added. 

I followed formatting pattern from projections (``ProjectionStatisticsHttpFormatted``). 

Disabled link is only returned when user is enabled (and vice versa, enable link only for disabled users).

Example for /users/:
```javascript
    {
      "data": [
        {
          "loginName": "test1",
          "fullName": "test1",
          "groups": [
            "$admins"
          ],
          "disabled": false,
          "links": [
            {
              "href": "http://127.0.0.1:2113/users/test1/command/reset-password",
              "rel": "reset-password"
            },
            {
              "href": "http://127.0.0.1:2113/users/test1/command/change-password",
              "rel": "change-password"
            },
            {
              "href": "http://127.0.0.1:2113/users/test1",
              "rel": "edit"
            },
            {
              "href": "http://127.0.0.1:2113/users/test1",
              "rel": "delete"
            },
            {
              "href": "http://127.0.0.1:2113/users/test1/command/disable",
              "rel": "disable"
            }
          ]
        },
        {
          "loginName": "test2",
          "fullName": "test2",
          "groups": [
            "$admins"
          ],
          "disabled": true,
          "links": [
            {
              "href": "http://127.0.0.1:2113/users/test2/command/reset-password",
              "rel": "reset-password"
            },
            {
              "href": "http://127.0.0.1:2113/users/test2/command/change-password",
              "rel": "change-password"
            },
            {
              "href": "http://127.0.0.1:2113/users/test2",
              "rel": "edit"
            },
            {
              "href": "http://127.0.0.1:2113/users/test2",
              "rel": "delete"
            },
            {
              "href": "http://127.0.0.1:2113/users/test2/command/enable",
              "rel": "enable"
            }
          ]
        }
      ],
      "success": true,
      "error": "Success",
      "msgTypeId": 116
    }
```
Example for /users/test1:
```javascript
{
   data:{
      loginName:"test1",
      fullName:"test1",
      groups:[
         "$admins"
      ],
      disabled:false,
      links:[
         {
            href:"http://127.0.0.1:2113/users/test1/command/reset-password",
            rel:"reset-password"
         },
         {
            href:"http://127.0.0.1:2113/users/test1/command/change-password",
            rel:"change-password"
         },
         {
            href:"http://127.0.0.1:2113/users/test1",
            rel:"edit"
         },
         {
            href:"http://127.0.0.1:2113/users/test1",
            rel:"delete"
         },
         {
            href:"http://127.0.0.1:2113/users/test1/command/disable",
            rel:"disable"
         }
      ]
   },
   success:true,
   error:"Success",
   msgTypeId:115
}
```

### CODE REVIEW

**Comment by gregoryyoung** [comment]
I dont see any tests or the client being updated in this...

**Comment by belczyk** [comment]
I updated tests in src/EventStore.Core.Tests/Http/Users/users.cs

How client should be updated? Do you want client to return this links?  
I can populate them in ``EventStore.ClientAPI.UserManagement.UserDtails``

**Comment by gregoryyoung** [comment]
I would imagine it would need to be reworked a bit to use the rel links not
to bookmark as it does now.

**Comment by belczyk** [comment]
OK, now I get what you meant by bookmarks. 

I will play with ClientAPI and see how much must be changed.,

**Comment by belczyk** [comment]
There is one thing, if client will get links from server then every operation will require one more round trip. For example to change password I will have to make request to GET user, then read links and make another request to change password. 

Is this OK? I see  another option like returning links from OPTIONS request on /users (HTTP 1.1 and 2.0 allows body entity in OPTIONS response) but then instead of links we have to return patterns like /users/{0}/command/change-password and have convention that first arg is replaced with resource id. It feels somehow wrong.

**Comment by jen20** [comment]
:+1: thanks @belczyk!

**Pull request merged**
