### PR TITLE
Avoid a gen2 allocation when scheduling a timer message

### PR DESCRIPTION
**Pull request by timothycoleman**
Changed: Adjustments to reduce allocations

### CODE REVIEW

**Comment by timothycoleman** [comment]
erm, ok second commit doesn't actually work

**Review by shaan1337 — COMMENTED** [review]
I'm not sure if i'm interpreting this correctly:

I've checked the IL and it seems that an action object is still created: 
```
    IL_0021: newobj       instance void class [System.Runtime]System.Action`2<class EventStore.Core.Services.TimerService.IScheduler, object>::.ctor(object, native int)
```

it appears that it first pushes a pointer to the required function on the stack (with `ldftn`), then always creates the action object.

Given that the `OnTimerCallback` function is not an anonymous function, it will have a predefined location on the heap, so it won't make a new allocation (whether or not it was a static method doesn't matter in this case)

it seems that the optimization would only apply if we were using an anonymous method

also, it seems that it would be a gen0 allocation here (but i think the title says gen2 because of the previous commit)

**Comment by shaan1337** [comment]
> erm, ok second commit doesn't actually work, removed it

just out of curiosity, why doesn't it work? (the code looked good)

**Review by shaan1337 — APPROVED** [review]
looks good after discussions with @timothycoleman :+1: 

the `newobj` instruction is actually executed only once after the change

**Comment by timothycoleman** [comment]
ya in a nutshell:

- it's (likely) gen2 because the action was allocated when the message is scheduled and then collected after the callback is called (some-many seconds later)
- there is still an allocation but the compiler caches it in a property so it is only once rather than one per schedule
- the other optimisation didn't work because Reply is actually generic. the original code called Reply<T> and the change actually called Reply<Message> and then the cast in the SendToThisEnvelope didn't work

**Review by thefringeninja — APPROVED** [review]

**Pull request merged**
