### PR TITLE
Fix for #1411, delete order stream when projection is deleted

### PR DESCRIPTION
**Pull request by regularcoder**

### CODE REVIEW

**Comment by hayley-jean** [comment]
Thank you for the PR @regularcoder 

The following tests are failing with Null reference exceptions :

```
EventStore.Projections.Core.Tests.Services.projections_manager.when_deleting_a_faulted_persistent_projection.a_projection_deleted_event_is_written
EventStore.Projections.Core.Tests.Services.projections_manager.when_deleting_a_faulted_persistent_projection.should_have_attempted_to_delete_the_checkpoint_stream
EventStore.Projections.Core.Tests.Services.projections_manager.when_deleting_a_faulted_persistent_projection.should_have_attempted_to_delete_the_emitted_streams_stream
```

If you want to run these tests locally for debugging, the command to use is `./run_tc_tests.sh .`
This test script includes the projection tests.

**Comment by regularcoder** [comment]
I made corrections to fix the broken tests. All tests appear to be passing now. Thank you for your help.

**Comment by pgermishuys** [comment]
Thanks @regularcoder for the changes. Would you mind squashing your commits. If it's asking too much, we don't mind merging and then just fixing the branch afterwards.

**Comment by regularcoder** [comment]
@pgermishuys sure, I squashed my commits into 844be40. Please take a look.

**Comment by pgermishuys** [comment]
@regularcoder, it appears that there are now 7 commits. If you need help squashing the commits, please don't hesitate to shout.

**Comment by regularcoder** [comment]
Help would be appreciated. The other commits were made to the repo by others after I opened my PR. I'm not sure why they are showing up in the PR.

Are you saying I should squash all those 7 commits into one even though they are not mine? Or should I just delete my cloned GitHub repository and start afresh?

**Comment by pgermishuys** [comment]
You want to make sure that you rebase off of an updated upstream release 4.0.3 branch.
```
git remote add upstream git@github.com:EventStore/EventStore.git
git fetch upstream
git checkout release-v4.0.3
git rebase upstream/release-v4.0.3 -i
```

The interactive rebase gives you the ability to pick and squash your commits.

If you want to talk about it, let me know which medium is good for you, skype, slack, gtalk, etc.

**Comment by regularcoder** [comment]
That did the trick. I appreciate the guidance, thank you.

**Comment by pgermishuys** [comment]
@regularcoder thanks for the PR. We are going to merge this.

This requires tests and this can be used as a reference. https://github.com/EventStore/EventStore/blob/release-v4.0.3/src/EventStore.Projections.Core.Tests/Services/projections_manager/when_deleting_a_persistent_projection.cs

Will add some tests after the merge.

**Pull request merged**
