### PR TITLE
Add Appveyor configuration file

### PR DESCRIPTION
**Pull request by jen20**

### CODE REVIEW

**Comment by dnauck** [comment]
+1

Do you also plan to provide "nightly" builds?

**Comment by jen20** [comment]
@dnauck the artefacts are available via Appveyor, yes. We've not yet discussed whether to provide official nightly builds. If we do we need to provide some way of making it incredibly explicit that those running them do at their own risk.

**Comment by dnauck** [comment]
I'm using SemVer for this as it make it clear, e.g. 3.4.0-dev vs. 3.4.0, etc.

**Comment by jen20** [comment]
That might work, it will need some scripts adapting, however. We may also have to adjust which attribute in the DLLs the version comes from in order to support a proper semver string.

**Pull request merged**
