### PR TITLE
Add how to resign or change leader in eventstore.

### PR DESCRIPTION
**Pull request by CindyLoMinChung**
Add how to resign or change a leader under maintenance documentation.

### CODE REVIEW

**Comment by alexeyzimarev** [comment]
This API endpoint is missing from the API docs, as well as the node restart (I think). Should we not add it there instead? Maybe, add this but reference to HTTP API docs?

**Comment by coloradomorrissey** [comment]
Do we agree this commit within the API docs should be approved, but we are not changing the Operations docs?  If we update the Operations docs (original commit), the opening paragraph stating "EventStoreDB requires regular maintenance with **three** operational concerns" should be updated to accommodate resigning a leader.

**Comment by coloradomorrissey** [comment]
@alexeyzimarev where should Cindy make these updates now that we've switched to Hope?

**Comment by alexeyzimarev** [comment]
It should go to master and cherry-pick to 23.10 and 24.6

**Comment by CindyLoMinChung** [comment]
Created a new pull request for this one: [](https://github.com/EventStore/EventStore/pull/4479) closing this pull request

**Pull request closed without merging**
