### PR TITLE
fixed system projection query update 

### PR DESCRIPTION
**Pull request by abdomohamed**
@hayley-jean I've created another PR for the projections issue, becuase previous one commits history was interfered with other commits, so it will be anonnying to squash my commits. So, I found it easy to create another PR though.

**Issue:** https://github.com/EventStore/EventStore/issues/1451
**Prev PR:** https://github.com/EventStore/EventStore/pull/1455

### CODE REVIEW

**Comment by abdomohamed** [comment]
@hayley-jean I run the failing test localy (EventStore.Core.Tests.Integration.when_a_single_node_is_restarted_multiple_times.should_be_a_different_epoch_for_every_startup) and it worked, so it seems either the test is flaky or something related to my change I couldn't understand what it is.

**Comment by abdomohamed** [comment]
Confirmed it's related to my change, it seems I wasn't actualy passing emitEnabled but now, once it's passed test failed. But I couldn't see relationship between them. Any clue, will be appreciated.

**Comment by hayley-jean** [comment]
@abdomohamed I can't seem to reproduce the test failure, are you still seeing it locally?

**Comment by abdomohamed** [comment]
@hayley-jean let me run the tests again, will keep you posted.

**Comment by abdomohamed** [comment]
@hayley-jean it seems all good now. Happy to merge 👍

**Comment by abdomohamed** [comment]
hey team, any update on this.

**Comment by hayley-jean** [comment]
Thanks @abdomohamed, apologies for taking so long

This looks good 👍

**Pull request merged**
