### PR TITLE
Fixes exception when requesting "https://127.0.0.1:2113/users" multiple times

### PR DESCRIPTION
**Pull request by dyowee**
This is for issue #2659 "Calling /users/ endpoint randomly results in server-side exception". Previously, the current user details is being read asynchronously while at the same time moving forward to the next event from the stream. This causes concurrent access to the internal users list/collection.

The fix was to complete adding the user details to the collection, before moving to the next event in the stream.

### CODE REVIEW

**Comment by dyowee** [comment]
Accidentally closed the PR.

**Review by thefringeninja — APPROVED** [review]
This seems to fix an issue we're having with a flaky test in the client repos.

**Review by avish0694 — APPROVED** [review]
Looks good after testing. No exception was logged after calling `/users/` endpoint multiple times and reading the current user details.

**Review by shaan1337 — APPROVED** [review]
Looks good :+1: thanks for this fix @dyowee!

Stress tested with:
```
for i in `seq 1 1000`; do curl --silent -u "admin:changeit" -k 'https://127.0.0.1:2113/users/' |jq -r '.data[].loginName' > ./login_test/$i & ; done
```

Then verified output with:
```
$ cat ./login_test/*|grep -e 'admin' -e 'ops'|wc -l
2000
```

No exceptions on server-side as well

**Comment by dyowee** [comment]
Thanks! :)

**Pull request merged**
