### PR TITLE
Add release for 20.6.0-rc

### PR DESCRIPTION
**Pull request by hayley-jean**

### CODE REVIEW

**Comment by endeffects** [comment]
20.6.0-rc? Is this the correct version?

**Comment by jageall** [comment]
Yes it is the correct version, we are changing our versioning strategy and release cadence. There will be a blog post on the site explaining both the versioning and the release strategy within the next few days

**Comment by arwinneil** [comment]
``` ini

BenchmarkDotNet=v0.12.0, OS=amzn 2
Intel Xeon Platinum 8175M CPU 2.50GHz, 1 CPU, 8 logical and 4 physical cores
.NET Core SDK=3.1.300
  [Host]     : .NET Core 3.1.4 (CoreCLR 4.700.20.20201, CoreFX 4.700.20.21406), X64 RyuJIT
  Job-JCNLDF : .NET Core 3.1.4 (CoreCLR 4.700.20.20201, CoreFX 4.700.20.21406), X64 RyuJIT

InvocationCount=1  MaxIterationCount=50  UnrollFactor=1  
WarmupCount=20  

``` 
```
|                       Type |                         Method | numberOfEvents | eventSize | batchSize | warmTcp |      Mean |     Error |     StdDev |     Median |
|--------------------------- |------------------------------- |--------------- |---------- |---------- |-------- |----------:|----------:|-----------:|-----------:|
|            TcpV6Benchmarks |           v6Tcp_v6Server_Write |           1000 |       100 |       100 |   False | 71.541 ms | 3.5492 ms |  7.1696 ms | 72.8597 ms |
|            TcpV6Benchmarks |            v6Tcp_v6Server_Read |           1000 |       100 |       100 |   False | 30.776 ms | 8.9258 ms | 17.6187 ms | 21.4978 ms |
|            TcpV6Benchmarks |           v6Tcp_v6Server_Write |           1000 |       100 |       100 |    True | 55.346 ms | 6.1370 ms | 12.3970 ms | 60.8137 ms |
|            TcpV6Benchmarks |            v6Tcp_v6Server_Read |           1000 |       100 |       100 |    True |  8.049 ms | 0.5235 ms |  0.9304 ms |  7.8596 ms |
|            TcpV6Benchmarks |           v6Tcp_v6Server_Write |           1000 |       100 |      1000 |   False | 45.445 ms | 6.5771 ms | 12.6719 ms | 46.9634 ms |
|            TcpV6Benchmarks |            v6Tcp_v6Server_Read |           1000 |       100 |      1000 |   False |  9.124 ms | 0.6528 ms |  1.2421 ms |  8.8281 ms |
|            TcpV6Benchmarks |           v6Tcp_v6Server_Write |           1000 |       100 |      1000 |    True | 33.130 ms | 8.4567 ms | 17.0829 ms | 36.9532 ms |
|            TcpV6Benchmarks |            v6Tcp_v6Server_Read |           1000 |       100 |      1000 |    True |  4.989 ms | 0.3694 ms |  0.7117 ms |  4.7661 ms |
|  TcpSubscriptionBenchmarks |  v6Tcp_v6Server_SubscribeToAll |           1000 |         ? |       100 |   False |  6.293 ms | 2.4306 ms |  4.8542 ms |  4.3291 ms |
|  TcpSubscriptionBenchmarks |  v6Tcp_v6Server_SubscribeToAll |           1000 |         ? |       100 |    True |  4.066 ms | 2.5064 ms |  4.9475 ms |  2.3359 ms |
|             GrpcBenchmarks |          v6Grpc_v6Server_Write |           1000 |       100 |         ? |       ? | 27.486 ms | 1.5750 ms |  3.1454 ms | 27.5252 ms |
|             GrpcBenchmarks |           v6Grpc_v6Server_Read |           1000 |       100 |         ? |       ? | 21.418 ms | 0.8672 ms |  1.7319 ms | 21.4181 ms |
|            TcpV6Benchmarks |           v6Tcp_v6Server_Write |           1000 |      1000 |       100 |   False | 86.766 ms | 2.0706 ms |  4.0871 ms | 86.3918 ms |
|            TcpV6Benchmarks |            v6Tcp_v6Server_Read |           1000 |      1000 |       100 |   False | 17.133 ms | 2.6294 ms |  5.0660 ms | 16.6650 ms |
|            TcpV6Benchmarks |           v6Tcp_v6Server_Write |           1000 |      1000 |       100 |    True | 70.842 ms | 6.3360 ms | 12.7990 ms | 75.2764 ms |
|            TcpV6Benchmarks |            v6Tcp_v6Server_Read |           1000 |      1000 |       100 |    True | 12.713 ms | 2.0331 ms |  4.0602 ms | 13.0542 ms |
|            TcpV6Benchmarks |           v6Tcp_v6Server_Write |           1000 |      1000 |      1000 |   False | 48.221 ms | 2.8881 ms |  5.8341 ms | 45.5479 ms |
|            TcpV6Benchmarks |            v6Tcp_v6Server_Read |           1000 |      1000 |      1000 |   False | 11.223 ms | 1.8658 ms |  3.2678 ms | 10.2061 ms |
|            TcpV6Benchmarks |           v6Tcp_v6Server_Write |           1000 |      1000 |      1000 |    True | 35.587 ms | 5.1563 ms | 10.4159 ms | 36.6790 ms |
|            TcpV6Benchmarks |            v6Tcp_v6Server_Read |           1000 |      1000 |      1000 |    True |  4.984 ms | 0.5339 ms |  1.0028 ms |  4.5648 ms |
|  TcpSubscriptionBenchmarks |  v6Tcp_v6Server_SubscribeToAll |           1000 |         ? |      1000 |   False |  1.423 ms | 0.8395 ms |  1.5971 ms |  0.8555 ms |
|  TcpSubscriptionBenchmarks |  v6Tcp_v6Server_SubscribeToAll |           1000 |         ? |      1000 |    True |        NA |        NA |         NA |         NA |
|             GrpcBenchmarks |          v6Grpc_v6Server_Write |           1000 |      1000 |         ? |       ? | 35.216 ms | 1.9504 ms |  3.8953 ms | 35.2204 ms |
|             GrpcBenchmarks |           v6Grpc_v6Server_Read |           1000 |      1000 |         ? |       ? | 21.302 ms | 0.6008 ms |  1.1860 ms | 21.2703 ms |
| GrpcSubscriptionBenchmarks | v6Grpc_v6Server_SubscribeToAll |           1000 |         ? |         ? |       ? | 22.432 ms | 0.8741 ms |  1.7456 ms | 22.4505 ms |

Benchmarks with issues:
  TcpSubscriptionBenchmarks.v6Tcp_v6Server_SubscribeToAll: Job-JCNLDF(InvocationCount=1, MaxIterationCount=50, UnrollFactor=1, WarmupCount=20) [numberOfEvents=1000, batchSize=1000, warmTcp=True]

**Comment by arwinneil** [comment]
``` ini

BenchmarkDotNet=v0.12.0, OS=amzn 2
Intel Xeon Platinum 8175M CPU 2.50GHz, 1 CPU, 8 logical and 4 physical cores
.NET Core SDK=3.1.300
  [Host]     : .NET Core 3.1.4 (CoreCLR 4.700.20.20201, CoreFX 4.700.20.21406), X64 RyuJIT
  Job-DLAIWH : .NET Core 3.1.4 (CoreCLR 4.700.20.20201, CoreFX 4.700.20.21406), X64 RyuJIT

InvocationCount=1  MaxIterationCount=50  UnrollFactor=1  
WarmupCount=20  

``` 
```
|                       Type |                         Method | numberOfEvents | eventSize | batchSize | warmTcp |       Mean |      Error |     StdDev |     Median |
|--------------------------- |------------------------------- |--------------- |---------- |---------- |-------- |-----------:|-----------:|-----------:|-----------:|
|            TcpV6Benchmarks |           v6Tcp_v6Server_Write |           1000 |       100 |       100 |   False |  75.162 ms |  1.7114 ms |  3.3782 ms |  74.790 ms |
|            TcpV6Benchmarks |            v6Tcp_v6Server_Read |           1000 |       100 |       100 |   False |  14.125 ms |  1.4328 ms |  2.8283 ms |  13.144 ms |
|            TcpV6Benchmarks |           v6Tcp_v6Server_Write |           1000 |       100 |       100 |    True |  68.360 ms | 16.7417 ms | 33.8191 ms |  58.468 ms |
|            TcpV6Benchmarks |            v6Tcp_v6Server_Read |           1000 |       100 |       100 |    True |   7.979 ms |  0.4787 ms |  0.8990 ms |   7.777 ms |
|            TcpV6Benchmarks |           v6Tcp_v6Server_Write |           1000 |       100 |      1000 |   False |  45.786 ms |  6.1564 ms | 11.7132 ms |  48.010 ms |
|            TcpV6Benchmarks |            v6Tcp_v6Server_Read |           1000 |       100 |      1000 |   False |   8.890 ms |  0.5057 ms |  0.9743 ms |   8.571 ms |
|            TcpV6Benchmarks |           v6Tcp_v6Server_Write |           1000 |       100 |      1000 |    True |  30.518 ms |  8.1792 ms | 16.3348 ms |  33.738 ms |
|            TcpV6Benchmarks |            v6Tcp_v6Server_Read |           1000 |       100 |      1000 |    True |   4.114 ms |  0.0795 ms |  0.1033 ms |   4.114 ms |
|  TcpSubscriptionBenchmarks |  v6Tcp_v6Server_SubscribeToAll |           1000 |         ? |       100 |   False |   5.529 ms |  1.7583 ms |  3.3877 ms |   4.964 ms |
|  TcpSubscriptionBenchmarks |  v6Tcp_v6Server_SubscribeToAll |           1000 |         ? |       100 |    True |         NA |         NA |         NA |         NA |
|             GrpcBenchmarks |          v6Grpc_v6Server_Write |           1000 |       100 |         ? |       ? |  25.131 ms |  1.0042 ms |  1.9105 ms |  24.724 ms |
|             GrpcBenchmarks |           v6Grpc_v6Server_Read |           1000 |       100 |         ? |       ? |  21.349 ms |  0.7925 ms |  1.5644 ms |  21.199 ms |
|            TcpV6Benchmarks |           v6Tcp_v6Server_Write |           1000 |      1000 |       100 |   False | 130.108 ms |  5.2519 ms |  9.9923 ms | 132.821 ms |
|            TcpV6Benchmarks |            v6Tcp_v6Server_Read |           1000 |      1000 |       100 |   False |  35.047 ms | 21.2627 ms | 41.4712 ms |  12.779 ms |
|            TcpV6Benchmarks |           v6Tcp_v6Server_Write |           1000 |      1000 |       100 |    True | 101.232 ms | 17.3445 ms | 35.0368 ms | 125.807 ms |
|            TcpV6Benchmarks |            v6Tcp_v6Server_Read |           1000 |      1000 |       100 |    True |   7.600 ms |  0.2299 ms |  0.4592 ms |   7.543 ms |
|            TcpV6Benchmarks |           v6Tcp_v6Server_Write |           1000 |      1000 |      1000 |   False |         NA |         NA |         NA |         NA |
|            TcpV6Benchmarks |            v6Tcp_v6Server_Read |           1000 |      1000 |      1000 |   False |   9.215 ms |  0.8046 ms |  1.5112 ms |   9.059 ms |
|            TcpV6Benchmarks |           v6Tcp_v6Server_Write |           1000 |      1000 |      1000 |    True |         NA |         NA |         NA |         NA |
|            TcpV6Benchmarks |            v6Tcp_v6Server_Read |           1000 |      1000 |      1000 |    True |   4.531 ms |  0.3002 ms |  0.5336 ms |   4.332 ms |
|  TcpSubscriptionBenchmarks |  v6Tcp_v6Server_SubscribeToAll |           1000 |         ? |      1000 |   False |   2.708 ms |  1.2431 ms |  2.3950 ms |   2.595 ms |
|  TcpSubscriptionBenchmarks |  v6Tcp_v6Server_SubscribeToAll |           1000 |         ? |      1000 |    True |         NA |         NA |         NA |         NA |
|             GrpcBenchmarks |          v6Grpc_v6Server_Write |           1000 |      1000 |         ? |       ? |  33.420 ms |  1.5285 ms |  3.0170 ms |  33.098 ms |
|             GrpcBenchmarks |           v6Grpc_v6Server_Read |           1000 |      1000 |         ? |       ? |  20.504 ms |  0.6805 ms |  1.3272 ms |  20.093 ms |
| GrpcSubscriptionBenchmarks | v6Grpc_v6Server_SubscribeToAll |           1000 |         ? |         ? |       ? |  21.098 ms |  0.7419 ms |  1.4645 ms |  20.925 ms |

Benchmarks with issues:
  TcpSubscriptionBenchmarks.v6Tcp_v6Server_SubscribeToAll: Job-DLAIWH(InvocationCount=1, MaxIterationCount=50, UnrollFactor=1, WarmupCount=20) [numberOfEvents=1000, batchSize=100, warmTcp=True]
  TcpV6Benchmarks.v6Tcp_v6Server_Write: Job-DLAIWH(InvocationCount=1, MaxIterationCount=50, UnrollFactor=1, WarmupCount=20) [numberOfEvents=1000, eventSize=1000, batchSize=1000, warmTcp=False]
  TcpV6Benchmarks.v6Tcp_v6Server_Write: Job-DLAIWH(InvocationCount=1, MaxIterationCount=50, UnrollFactor=1, WarmupCount=20) [numberOfEvents=1000, eventSize=1000, batchSize=1000, warmTcp=True]
  TcpSubscriptionBenchmarks.v6Tcp_v6Server_SubscribeToAll: Job-DLAIWH(InvocationCount=1, MaxIterationCount=50, UnrollFactor=1, WarmupCount=20) [numberOfEvents=1000, batchSize=1000, warmTcp=True]

**Pull request merged**
