### PR TITLE
Remove Client API From Main Project

### PR DESCRIPTION
**Pull request by thefringeninja**
Changed: TCP client moved from main repo to https://github.com/EventStore/EventStoreDB-Client-Dotnet-Legacy

Part of EventStore/home#410

### CODE REVIEW

**Review by YoEight — APPROVED** [review]
Godspeed

**Review by YoEight — APPROVED** [review]

**Review by hayley-jean — CHANGES_REQUESTED** [review]
@thefringeninja The changes look good, but the [EventStore/EventStoreDB-Client-Dotnet-Legacy](https://github.com/EventStore/EventStoreDB-Client-Dotnet-Legacy) repo is empty at the moment.

Could you push up the client to that repo before we merge this PR?

**Comment by thefringeninja** [comment]
@hayley-jean,

EventStore/EventStoreDB-Client-Dotnet-Legacy#1

**Review by hayley-jean — APPROVED** [review]

**Comment by hayley-jean** [comment]
@thefringeninja Thanks! This looks good to merge once the merge conflicts are resolved

**Review by hayley-jean — APPROVED** [review]

**Review by YoEight — APPROVED** [review]

**Pull request merged**
